#!/usr/bin/env python3
"""Quantise the trained net to int8 and write digit-model.js.

Per-tensor symmetric quantisation: one float scale per weight tensor, weights as
int8, biases left as float32. That is about a quarter the size of float32 for a
fraction of a percent of accuracy, and dequantising costs ten lines in the browser.

Biases stay float32 on purpose - there are only 66 of them, so quantising them
saves nothing measurable and costs accuracy.

Usage:
  python3 tools/export_weights.py --model tools/digit-model.npz --out digit-model.js
"""

import argparse
import base64
import json
import os

import numpy as np

WEIGHTS = ["w1", "w2", "w3", "w4"]
BIASES = ["b1", "b2", "b3", "b4"]


def quantise(tensor):
    peak = float(np.abs(tensor).max())
    scale = peak / 127.0 if peak else 1.0
    q = np.clip(np.rint(tensor / scale), -127, 127).astype(np.int8)
    error = float(np.abs(q.astype(np.float32) * scale - tensor).max())
    return q, scale, error


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="tools/digit-model.npz")
    ap.add_argument("--out", default="digit-model.js")
    args = ap.parse_args()

    data = np.load(args.model)
    payload, scales, report = {}, {}, []
    for name in WEIGHTS:
        q, scale, error = quantise(data[name])
        payload[name] = base64.b64encode(q.tobytes()).decode("ascii")
        scales[name] = scale
        report.append((name, data[name].shape, q.size, error, float(np.abs(data[name]).max())))

    biases = {name: [round(float(v), 6) for v in data[name]] for name in BIASES}
    total_params = sum(data[n].size for n in WEIGHTS + BIASES)

    js = """// Generated by tools/export_weights.py - do not edit by hand.
//
// Digit classifier for vision.js: conv3x3x8 -> pool -> conv3x3x16 -> pool ->
// dense 32 -> dense 10, %d parameters. Class 0 is background (junk that gets
// past the empty-cell filter); classes 1-9 are the digits.
//
// Weights are int8 with one float scale per tensor; biases are float32.
var SudokuDigitModel = (function () {
  'use strict';

  var SCALES = %s;
  var PACKED = %s;
  var BIASES = %s;

  function decode(b64, scale) {
    var binary = typeof atob === 'function'
      ? atob(b64)
      : Buffer.from(b64, 'base64').toString('binary');
    var out = new Float32Array(binary.length);
    for (var i = 0; i < binary.length; i++) {
      var byte = binary.charCodeAt(i);
      out[i] = (byte > 127 ? byte - 256 : byte) * scale;   // int8 is two's complement
    }
    return out;
  }

  var cache = null;

  return {
    arch: 'conv8-pool-conv16-pool-dense32-dense10',
    inputSize: 28,
    classes: 10,
    params: %d,
    // Dequantised once, then reused. Returns { w1..w4, b1..b4 } as Float32Arrays.
    weights: function () {
      if (cache) { return cache; }
      cache = {
        w1: decode(PACKED.w1, SCALES.w1), b1: Float32Array.from(BIASES.b1),
        w2: decode(PACKED.w2, SCALES.w2), b2: Float32Array.from(BIASES.b2),
        w3: decode(PACKED.w3, SCALES.w3), b3: Float32Array.from(BIASES.b3),
        w4: decode(PACKED.w4, SCALES.w4), b4: Float32Array.from(BIASES.b4)
      };
      return cache;
    }
  };
})();

if (typeof module !== 'undefined' && module.exports) { module.exports = SudokuDigitModel; }
""" % (total_params,
       json.dumps({k: round(v, 12) for k, v in scales.items()}, indent=2),
       json.dumps(payload, indent=2),
       json.dumps(biases),
       total_params)

    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(js)

    print("quantisation:")
    for name, shape, count, error, peak in report:
        print("  %-3s %-12s %6d weights  peak |w| %.4f  max error %.5f (%.2f%% of peak)"
              % (name, "x".join(map(str, shape)), count, peak, error,
                 100 * error / peak if peak else 0))
    print("\n%d parameters -> %s, %.1f KB" % (total_params, args.out,
                                              os.path.getsize(args.out) / 1024))


if __name__ == "__main__":
    main()
